name: Update tracks
on:
  schedule:
    - cron: "0 19 * * 1"
permissions:
  contents: write
  pull-requests: write
jobs:
  tracks:
    name: Search and update new tracks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install homeassistant
      - name: Update tracks
        env:
          GROUNDED_TOKEN: ${{ secrets.GROUNDED_TOKEN }}
        run: python update_tracks.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update tracks
          title: Update tracks
          body: Update tracks
          base: main
          labels: automated-pr, tracks
          branch: update-tracks
